package main

import (
	"log"

	"github.com/go-kvolt/kvolt"
	"github.com/go-kvolt/kvolt/context"
	"github.com/go-kvolt/kvolt/middleware"
	"github.com/go-kvolt/kvolt/pkg/swagger"

	_ "test/docs" // docs is generated by Swag CLI, you have to import it.
	"test/internal/handler"
)

// @title           KVolt Test API
// @version         1.0
// @description     This is a sample server using KVolt.
// @host            localhost:8080
// @BasePath        /
func main() {
	app := kvolt.New()

	app.Use(middleware.Logger())

	app.GET("/", func(c *context.Context) error {
		return c.JSON(200, map[string]string{"msg": "Hello KVolt"})
	})

	// Serve Static Files
	app.Static("/static", "./public")

	// User Routes
	app.GET("/users", handler.GetUsers)
	app.GET("/users/:id", handler.GetUser)
	app.PUT("/users/:id", handler.UpdateUser)
	app.DELETE("/users/:id", handler.DeleteUser)
	app.POST("/users", handler.CreateUser)

	// Post Routes
	app.GET("/posts", handler.GetPosts)
	app.POST("/posts", handler.CreatePost)

	// Misc Routes
	app.GET("/health", handler.GetHealth)
	app.GET("/version", handler.GetVersion)

	// Swagger Route
	// Swagger Route
	// doc, _ := swag.ReadDoc() // Read from "swagger" instance by default

	app.GET("/swagger/*any", swagger.Handler(swagger.Config{
		// SpecJSON: doc, // Commented out to demonstrate Auto-Docs
		RoutesProvider: &kvoltAdapter{engine: app},
		Title:          "KVolt Auto-Docs Demo",
		Host:           "localhost:8080",
	}))

	log.Println("Server starting on :8080")
	app.Run(":8080")
}

// Adapter to convert kvolt.Engine to swagger.RouteProvider
type kvoltAdapter struct {
	engine *kvolt.Engine
}

func (a *kvoltAdapter) Routes() []swagger.RouteInfo {
	kvoltRoutes := a.engine.Routes()
	var routes []swagger.RouteInfo
	for _, r := range kvoltRoutes {
		routes = append(routes, swagger.RouteInfo{
			Method:  r.Method,
			Path:    r.Path,
			Summary: r.Summary,
		})
	}
	return routes
}
